package JinRyuu.DragonBC.common.m;

import JinRyuu.DragonBC.common.Blocks.m.ModdedBlocks;
import java.util.Random;
import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenAbstractTree;

public class WorldGenMapleTree extends WorldGenAbstractTree {
   public boolean b = false;

   public WorldGenMapleTree() {
      super(false);
      this.b = false;
   }

   public WorldGenMapleTree(boolean b) {
      super(false);
      this.b = b;
   }

   public boolean func_76484_a(World world, Random random, int x, int y, int z) {
      if (this.b) {
         while(world.func_147437_c(x, y, z) && y > 2) {
            --y;
         }
      } else {
         --y;
      }

      Block block = world.func_147439_a(x, y, z);
      if (block != Blocks.field_150349_c && block != Blocks.field_150346_d) {
         return false;
      } else if (world.func_147437_c(x, y, z)) {
         return false;
      } else {
         int baselength = 0 + random.nextInt(1);
         int branches = 1;
         int h = 1;
         block.onPlantGrow(world, x, y, z, x, y, z);

         int dec;
         for(dec = 0; dec < baselength; ++dec) {
            this.buildBlock(world, x, y + h, z, ModdedBlocks.SakuraLogs, 2);
            ++h;
         }

         dec = random.nextInt(2);
         int c;
         int i;
         if (dec == 0) {
            c = 1;

            for(i = 0; i < branches; ++i) {
               this.generateTreeOne(world, random, x, y + h, z, c);
               ++c;
               h += 2;
            }
         } else if (dec == 1) {
            c = 1;

            for(i = 0; i < branches; ++i) {
               this.generateTreeTwo(world, random, x, y + h, z, c);
               ++c;
               h += 2;
            }
         }

         return true;
      }
   }

   private void generateTreeTwo(World world, Random random, int i, int j, int k, int c) {
      this.buildBlock(world, i - 4, j + 6, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 4, j + 6, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 4, j + 7, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 3, j + 4, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 3, j + 4, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 3, j + 5, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 3, j + 5, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 3, j + 5, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 3, j + 6, k - 5, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 3, j + 6, k - 4, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i - 3, j + 6, k - 3, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i - 3, j + 6, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 3, j + 7, k - 5, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 3, j + 7, k - 4, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i - 3, j + 7, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 3, j + 8, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 2, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 3, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 3, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 4, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 4, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 4, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 4, k, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 5, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 5, k - 3, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i - 2, j + 5, k - 2, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i - 2, j + 5, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 5, k, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 6, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 6, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 6, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 6, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 7, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 7, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 7, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 7, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 8, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 3, k - 1, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i - 1, j + 3, k, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 4, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 4, k - 1, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i - 1, j + 4, k, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 4, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 5, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 5, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 5, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 5, k, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 5, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 6, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 6, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 6, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 6, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 6, k, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 7, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 7, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 7, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 7, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 8, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 8, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 0, k, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i, j + 1, k, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i, j + 2, k, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i, j + 2, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 3, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 3, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 3, k - 1, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i, j + 3, k, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 3, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 4, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 4, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 4, k, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 4, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 5, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 5, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 5, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 5, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 5, k, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 5, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 5, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 6, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 6, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 6, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 6, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 6, k, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 6, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 6, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 7, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 7, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 7, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 7, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 8, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 8, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i, j + 8, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 2, k, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 1, j + 3, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 3, k, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 1, j + 4, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 4, k, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 5, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 5, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 5, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 5, k, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 5, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 6, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 6, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 6, k, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 7, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 7, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 7, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 7, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 7, k, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 7, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 8, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 8, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 2, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 3, k, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 3, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 3, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 4, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 4, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 4, k, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 2, j + 4, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 5, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 5, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 5, k, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 2, j + 5, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 6, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 6, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 6, k, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 7, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 7, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 7, k, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 8, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 4, k, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 4, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 5, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 5, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 5, k, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 3, j + 5, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 6, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 6, k, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 3, j + 6, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 7, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 7, k, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 3, j + 7, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 8, k, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 3, k, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 3, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 4, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 4, k, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 5, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 5, k, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 5, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 6, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 6, k, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 7, k, ModdedBlocks.MapleLeafs, 0);
   }

   private void generateTreeOne(World world, Random random, int i, int j, int k, int c) {
      this.buildBlock(world, i - 5, j + 6, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 5, j + 7, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 5, j + 7, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 5, j + 8, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 5, j + 9, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 5, j + 10, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 4, j + 5, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 4, j + 6, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 4, j + 6, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 4, j + 7, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 4, j + 7, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 4, j + 7, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 4, j + 8, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 4, j + 8, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 4, j + 8, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 4, j + 9, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 4, j + 9, k + 0, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i - 4, j + 9, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 4, j + 9, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 4, j + 10, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 4, j + 10, k + 0, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i - 4, j + 10, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 4, j + 11, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 3, j + 6, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 3, j + 7, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 3, j + 7, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 3, j + 7, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 3, j + 7, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 3, j + 8, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 3, j + 8, k + 0, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i - 3, j + 8, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 3, j + 8, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 3, j + 9, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 3, j + 9, k + 0, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i - 3, j + 9, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 3, j + 9, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 3, j + 10, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 3, j + 10, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 3, j + 10, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 3, j + 10, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 3, j + 10, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 3, j + 11, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 3, j + 11, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 5, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 6, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 6, k + 0, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i - 2, j + 7, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 7, k + 0, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i - 2, j + 7, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 8, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 8, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 8, k + 0, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i - 2, j + 8, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 8, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 9, k - 5, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 9, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 9, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 9, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 9, k + 0, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i - 2, j + 9, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 9, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 10, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 10, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 10, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 10, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 10, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 10, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 11, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 11, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 11, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 11, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 2, j + 12, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 3, k - 7, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 4, k - 7, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 4, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 4, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 4, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 5, k - 7, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 5, k - 6, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 5, k + 0, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i - 1, j + 6, k - 6, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 6, k - 5, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 6, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 6, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 6, k + 0, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i - 1, j + 7, k - 6, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 7, k - 5, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 7, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 7, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 8, k - 6, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 8, k - 5, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 8, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 8, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 8, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 8, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 8, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 8, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 8, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 9, k - 6, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 9, k - 5, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 9, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 9, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 9, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 9, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 9, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 9, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 10, k - 5, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 10, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 10, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 10, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 10, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 10, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 10, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 11, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 11, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 11, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 11, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 11, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 12, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 12, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i - 1, j + 13, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 0, k + 0, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 0, j + 1, k + 0, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 0, j + 2, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 2, k + 0, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 0, j + 3, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 3, k - 3, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 0, j + 3, k - 2, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 0, j + 3, k - 1, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 0, j + 3, k + 0, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 0, j + 4, k - 5, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 4, k - 4, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 0, j + 4, k - 3, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 0, j + 4, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 4, k + 0, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 0, j + 5, k - 6, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 5, k - 5, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 0, j + 5, k - 4, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 0, j + 5, k + 0, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 0, j + 5, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 6, k - 6, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 6, k - 5, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 0, j + 6, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 6, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 6, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 6, k + 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 7, k - 7, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 7, k - 6, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 0, j + 7, k - 5, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 0, j + 7, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 7, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 7, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 7, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 7, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 7, k + 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 8, k - 7, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 8, k - 6, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 0, j + 8, k - 5, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 8, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 8, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 8, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 8, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 8, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 8, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 9, k - 7, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 9, k - 6, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 0, j + 9, k - 5, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 9, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 9, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 9, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 9, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 9, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 9, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 9, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 10, k - 6, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 10, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 10, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 10, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 10, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 10, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 11, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 11, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 11, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 11, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 11, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 11, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 12, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 12, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 12, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 0, j + 13, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 3, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 4, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 4, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 4, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 5, k - 6, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 5, k - 5, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 5, k + 0, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 1, j + 6, k - 5, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 6, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 6, k + 0, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 1, j + 7, k - 6, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 7, k - 5, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 7, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 7, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 7, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 8, k - 6, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 8, k - 5, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 8, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 8, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 8, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 8, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 8, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 8, k + 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 9, k - 6, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 9, k - 5, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 9, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 9, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 9, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 9, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 9, k + 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 10, k - 6, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 10, k - 5, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 10, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 10, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 10, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 10, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 10, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 10, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 10, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 11, k - 6, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 11, k - 5, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 11, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 11, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 11, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 11, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 11, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 1, j + 11, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 3, k - 5, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 4, k - 5, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 5, k - 5, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 5, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 6, k + 0, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 2, j + 7, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 7, k + 0, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 2, j + 7, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 7, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 7, k + 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 8, k - 6, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 8, k - 5, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 8, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 8, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 8, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 8, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 8, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 8, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 8, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 8, k + 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 9, k - 5, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 9, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 9, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 9, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 9, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 9, k + 0, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 2, j + 9, k + 1, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 2, j + 9, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 9, k + 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 10, k - 5, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 10, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 10, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 10, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 10, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 10, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 10, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 10, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 10, k + 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 11, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 11, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 11, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 11, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 11, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 11, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 12, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 2, j + 12, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 6, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 7, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 7, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 7, k + 0, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 3, j + 7, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 8, k - 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 8, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 8, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 8, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 8, k + 0, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 3, j + 8, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 8, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 8, k + 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 9, k - 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 9, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 9, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 9, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 9, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 9, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 9, k + 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 10, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 10, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 10, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 10, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 10, k + 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 11, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 11, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 11, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 11, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 12, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 3, j + 12, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 6, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 7, k - 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 7, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 7, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 7, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 8, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 8, k + 0, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 4, j + 8, k + 1, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 4, j + 8, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 8, k + 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 9, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 9, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 9, k + 1, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 4, j + 9, k + 2, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 4, j + 9, k + 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 10, k - 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 10, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 10, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 10, k + 2, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 4, j + 10, k + 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 11, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 11, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 11, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 11, k + 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 12, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 12, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 12, k + 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 13, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 4, j + 13, k + 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 5, j + 6, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 5, j + 7, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 5, j + 7, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 5, j + 7, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 5, j + 7, k + 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 5, j + 8, k + 0, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 5, j + 8, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 5, j + 8, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 5, j + 9, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 5, j + 9, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 5, j + 9, k + 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 5, j + 10, k + 1, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 5, j + 10, k + 2, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 5, j + 10, k + 3, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 5, j + 10, k + 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 5, j + 11, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 5, j + 11, k + 3, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 5, j + 11, k + 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 5, j + 12, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 5, j + 12, k + 3, ModdedBlocks.SakuraLogs, 2);
      this.buildBlock(world, i + 5, j + 12, k + 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 5, j + 13, k + 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 6, j + 10, k + 2, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 6, j + 10, k + 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 6, j + 11, k + 3, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 6, j + 11, k + 4, ModdedBlocks.MapleLeafs, 0);
      this.buildBlock(world, i + 6, j + 12, k + 3, ModdedBlocks.MapleLeafs, 0);
   }

   public void buildBlock(World world, int x, int y, int z, Block block, int meta) {
      if (world.func_147437_c(x, y, z) || world.func_147439_a(x, y, z).isLeaves(world, x, y, z)) {
         world.func_147465_d(x, y, z, block, meta, 2);
      }

   }
}
